spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/deltaforge
    username: postgres
    password: banana
  jackson:
    default-property-inclusion: non_null
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
  data:
    rest:
      base-path: api/v1
      return-body-on-create: true
      return-body-on-update: true
      default-media-type: application/json
      default-page-size: 100
      max-page-size: 1000
      enable-enum-translation: true

logging:
  level:
    net.brutus5000: DEBUG

deltaforge:
  root-repository-path: ./data
  baseline-filesize-threshold: 1000