spring:
  datasource:
    url: jdbc:h2:mem:deltaforge
    username: sa
    password:
  jackson:
    default-property-inclusion: non_null
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
  data:
    rest:
      base-path: api/v1
      return-body-on-create: true
      return-body-on-update: true
      default-media-type: application/json
      default-page-size: 100
      max-page-size: 1000
      enable-enum-translation: true

logging:
  level:
    net.brutus5000: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%36.36X{requestId:- no request context}]){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
deltaforge:
  root-repository-path: ./data
  baseline-filesize-threshold: 1000