spring:
  jackson:
    default-property-inclusion: non_null
logging:
  level:
    net.brutus5000: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%36.36X{requestId:- no request context}]){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

deltaforge:
  security:
    auth-token-header-name: x-api-key
    auth-token: ${API_KEY}
  root-repository-path: ${ROOT_REPOSITORY_PATH}
